services:
  cypress:
    build: .
    working_dir: /e2e
    volumes:
      - .:/e2e
      - /e2e/node_modules   # prevents overwriting node_modules with host version
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - CYPRESS_CACHE_FOLDER=/home/cypress/.cache/Cypress
    command: >
      npx cypress run --browser electron
