name: Cypress Cucumber Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # (Optional) Start your app here if it's part of the repo
      - name: Build and run app
        run: |
          docker build -t my-app ./app
          docker run -d -p 3000:3000 --name app my-app

      - name: Wait for app to be healthy
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000/health; then
              echo "App is healthy!"
              exit 0
            fi
            echo "Waiting for app..."
            sleep 5
          done
          echo "App did not become healthy in time" && exit 1

      - name: Build Cypress Docker Image
        run: docker build -t cucumber-cypress-tests .

      - name: Run Cypress Cucumber Tests
        run: docker run --rm --network host cucumber-cypress-tests
